# Generated by Django 4.2.3 on 2023-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=255)),
                ('register_email', models.EmailField(max_length=255)),
                ('register_number', models.CharField(max_length=255)),
                ('register_user', models.CharField(max_length=255)),
                ('register_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
