# Generated by Django 4.1.3 on 2023-08-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_cart_product_price_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
