# Generated by Django 4.1.3 on 2023-09-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cart_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='register_pass',
            new_name='password',
        ),
    ]
