# Generated by Django 4.1.3 on 2023-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_register_pass_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
