# Generated by Django 4.1.3 on 2023-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
