# Generated by Django 4.2.3 on 2023-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='register_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
