# Generated by Django 4.2.3 on 2023-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_registration_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='register_image',
        ),
    ]
