# Generated by Django 4.2.3 on 2023-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_registration_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('product_image', models.CharField(max_length=255, null=True)),
                ('cat_pro_count', models.IntegerField()),
            ],
        ),
    ]
