# Generated by Django 4.2.3 on 2023-09-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_image',
            new_name='cat_image',
        ),
    ]
