# Generated by Django 4.1.3 on 2023-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_product_image_category_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.TextField(null=True),
        ),
    ]
