# Generated by Django 4.1.3 on 2023-09-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_registration_register_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='register_propic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
