# Generated by Django 4.2.5 on 2023-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_product_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
    ]
