# Generated by Django 4.2.5 on 2023-09-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0024_remove_product_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_desc",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
