# Generated by Django 4.2.5 on 2023-09-28 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0025_cart_product_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product_desc",
            new_name="cart_desc",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="product_id",
            new_name="cart_id",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="product_image",
            new_name="cart_image",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="product_name",
            new_name="cart_name",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="product_price",
            new_name="cart_price",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="product_quantity",
            new_name="cart_quantity",
        ),
    ]
