# Generated by Django 4.2.5 on 2023-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_alter_cart_cart_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("prod_name", models.CharField(max_length=255)),
                ("prod_qty", models.IntegerField()),
                ("prod_price", models.FloatField()),
                ("prod_tot", models.FloatField(default=0)),
                ("cust_user", models.CharField(max_length=255)),
                ("deliv_address", models.TextField()),
                ("deliv_type", models.CharField(max_length=255)),
                ("order_status", models.CharField(max_length=255)),
                ("deliv_status", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Checkout",
        ),
    ]
