# Generated by Django 4.2.5 on 2023-09-29 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0030_alter_order_deliv_status_alter_order_deliv_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
    ]
